{
  "formatVersion": "1.1",
  "component": {
    "group": "com.arun.libs",
    "module": "HappyYou",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "21.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.mikhaellopez",
          "module": "circularprogressbar",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.balysv",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "io.github.stringcare",
          "module": "library",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fitness",
          "version": {
            "requires": "20.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "19.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.aabhasr1",
          "module": "OtpView",
          "version": {
            "requires": "v1.1.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.cachapa",
          "module": "ExpandableLayout",
          "version": {
            "requires": "2.9.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.esafirm.android-image-picker",
          "module": "imagepicker",
          "version": {
            "requires": "2.4.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.1gravity",
          "module": "android-contactpicker",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.1.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-dynamic-links",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth",
          "version": {
            "requires": "21.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "version": {
            "requires": "21.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "CarouselView",
          "version": {
            "requires": "1.2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.pierfrancescosoffritti.androidyoutubeplayer",
          "module": "core",
          "version": {
            "requires": "12.1.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "f79a8955ef"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "rpp_common",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "rppg_core",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha20"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.iamareebjamal",
          "module": "opencv-android",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.skymansandy",
          "module": "scratchCardLayout",
          "version": {
            "requires": "v1.0.8"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.mofneko",
          "module": "EmulatorDetector",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.mhiew",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "3.2.0-beta.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.yuriy-budiyev",
          "module": "code-scanner",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.3llomi",
          "module": "hidely",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.squti",
          "module": "Android-Wave-Recorder",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.BelooS",
          "module": "ChipsLayoutManager",
          "version": {
            "requires": "v0.3.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-alpha07"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.trackier",
          "module": "android-sdk",
          "version": {
            "requires": "1.6.64"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "HappyYou-1.0.0.aar",
          "url": "HappyYou-1.0.0.aar",
          "size": 36608816,
          "sha512": "d6317dd330f5f58a75fe58f179f9718fbe40f6fd8e246844e39175a3e2a2d7aa505618944477dfc3969012962f7dfcccb8e7e38e2b3bd81cce82502bf3189b98",
          "sha256": "ce46813c41f38b110e67b726cef90289eddc2c606dfe675e28e951c36743c2cd",
          "sha1": "e3632d619cd7476328757fbce44ad04146964d1d",
          "md5": "43f36f3c9e3c1ce2c1c87c99e6e89e6c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-config",
          "version": {
            "requires": "21.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.mikhaellopez",
          "module": "circularprogressbar",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.balysv",
          "module": "material-ripple",
          "version": {
            "requires": "1.0.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.PhilJay",
          "module": "MPAndroidChart",
          "version": {
            "requires": "v3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "io.github.stringcare",
          "module": "library",
          "version": {
            "requires": "4.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fitness",
          "version": {
            "requires": "20.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "19.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.aabhasr1",
          "module": "OtpView",
          "version": {
            "requires": "v1.1.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.4.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth-api-phone",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.cachapa",
          "module": "ExpandableLayout",
          "version": {
            "requires": "2.9.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "de.hdodenhof",
          "module": "circleimageview",
          "version": {
            "requires": "3.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.esafirm.android-image-picker",
          "module": "imagepicker",
          "version": {
            "requires": "2.4.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.1gravity",
          "module": "android-contactpicker",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.13.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "31.1.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-messaging",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-crashlytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.8.5"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-dynamic-links",
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-auth",
          "version": {
            "requires": "21.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-analytics",
          "version": {
            "requires": "21.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "jp.wasabeef",
          "module": "glide-transformations",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "CarouselView",
          "version": {
            "requires": "1.2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.pierfrancescosoffritti.androidyoutubeplayer",
          "module": "core",
          "version": {
            "requires": "12.1.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "5.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.florent37",
          "module": "viewtooltip",
          "version": {
            "requires": "f79a8955ef"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "28.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "rpp_common",
          "version": {
            "requires": "0.5.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.arun.libs",
          "module": "rppg_core",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc01"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha20"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.mlkit",
          "module": "face-detection",
          "version": {
            "requires": "16.0.3"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.neovisionaries",
          "module": "nv-websocket-client",
          "version": {
            "requires": "2.4"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.iamareebjamal",
          "module": "opencv-android",
          "version": {
            "requires": "4.3.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.skymansandy",
          "module": "scratchCardLayout",
          "version": {
            "requires": "v1.0.8"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.18.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.intuit.sdp",
          "module": "sdp-android",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.9.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.mofneko",
          "module": "EmulatorDetector",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.scottyab",
          "module": "rootbeer-lib",
          "version": {
            "requires": "0.1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.mhiew",
          "module": "android-pdf-viewer",
          "version": {
            "requires": "3.2.0-beta.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.yuriy-budiyev",
          "module": "code-scanner",
          "version": {
            "requires": "2.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.journeyapps",
          "module": "zxing-android-embedded",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.2.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.flexbox",
          "module": "flexbox",
          "version": {
            "requires": "3.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.3llomi",
          "module": "hidely",
          "version": {
            "requires": "1.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.karumi",
          "module": "dexter",
          "version": {
            "requires": "6.2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.squti",
          "module": "Android-Wave-Recorder",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.github.BelooS",
          "module": "ChipsLayoutManager",
          "version": {
            "requires": "v0.3.7"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.2.0-alpha05"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.1.0-alpha07"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.trackier",
          "module": "android-sdk",
          "version": {
            "requires": "1.6.64"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "7.4.2"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          },
          "excludes": [
            {
              "group": "com.google.android.gms",
              "module": "play-services-safetynet"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "HappyYou-1.0.0.aar",
          "url": "HappyYou-1.0.0.aar",
          "size": 36608816,
          "sha512": "d6317dd330f5f58a75fe58f179f9718fbe40f6fd8e246844e39175a3e2a2d7aa505618944477dfc3969012962f7dfcccb8e7e38e2b3bd81cce82502bf3189b98",
          "sha256": "ce46813c41f38b110e67b726cef90289eddc2c606dfe675e28e951c36743c2cd",
          "sha1": "e3632d619cd7476328757fbce44ad04146964d1d",
          "md5": "43f36f3c9e3c1ce2c1c87c99e6e89e6c"
        }
      ]
    }
  ]
}
